<div class="footer">
	<div class="footer-1">
	   <h3> Download our app</h3>
	   <p>Our purpose is to provide people with the best quality products.<br>
		  Visit our shop or download our app on iOS or Android mobile.</p>
	</div>

	<h3> Follow Us </h3>
	<div class="footer-2">
	   <div class="footer2-col">
		  <p><strong>Facebook</strong></p>
		  <img src="stylesheet/images/facebook.webp"alt=""width="50"height="50">
	   </div>        
	   <div class="footer2-col">
		  <p><strong>Instagram</strong></p>
		  <img src="stylesheet/images/instagramlogo.png" alt="" width="50"height="50">
	   </div>
	   <div class="footer2-col">
		  <p><strong>LinkedIn</strong></p>
		  <img src="stylesheet/images/linkedin.png" alt="" width="50"height="50">
	   </div>  
	</div>

	<div class ="copyright">
	   <p><strong><br/>Project by Pixel-8 </strong></p>
	   <p>Copyright 2022- Pixel-8. All rights reserved.</p>
	</div>
</div>